apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - helmrelease.yaml
  - mariadb-operator-helmrepo.yaml
  - mariadb-operator-helmrelease.yaml
  - namespace.yaml
