apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: course-app-staging
  namespace: flux-system
spec:
  interval: 1m              
  path: ./overlays/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system       
  targetNamespace: staging 