apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordp.fullname" . }}
  labels:
    {{- include "wordp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wordp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordp.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
              containerPort: {{ .Values.service.port }}

          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}

          envFrom:
            - configMapRef:
                name: {{ include "wordp.fullname" . }}-config
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 2