apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wordp.fullname" . }}
  labels:
    {{- include "wordp.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "wordp.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}